name: Apply

on:
  workflow_dispatch:

jobs:
  tf-validate:
    name: Terraform validate and format check
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup project
        run: make terraform-init

      - name: Validate terraform files
        run: make terraform-validate


  tf-deploy:
    name: Terraform apply
    needs: [tf-validate]
    runs-on: ubuntu-latest
    env:
      OS: linux
      COPS_URL: ${{ secrets.COPS_HOST_PROD }}
      TF_VAR_registry_host: ${{ secrets.CONTAINER_REGISTRY_HOST }}
      TF_VAR_image_tag: ${{ needs.release.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Init project
        run: make terraform-init

      - name: Terraform plan
        run: make terraform-plan

      - name: Terraform apply
        run: make terraform-apply
